### ISSUE TITLE
Connection Pool is not well configured in the source

### ISSUE THREAD

**Issue by edgars** [wso2/carbon-datasources#51]
Hi,

I believe there is a mistake in that line, could someone please review it? 

https://github.com/wso2/carbon-datasources/blob/0f75644c2dd6da7744103e82038779c040b2c755/components/org.wso2.carbon.datasource.core/src/main/java/org/wso2/carbon/datasource/rdbms/hikari/utils/HikariDataSourceUtils.java#L56

**Comment by chanikag** [comment]
This is not used in MI, instead using
https://github.com/wso2/micro-integrator/tree/master/components/org.wso2.micro.integrator.ndatasource.core
